### ISSUE TITLE
Tiny turtle plan is no longer available

### ISSUE THREAD

**Issue by Vinestro89** [valentin-mille/RoadmapBackend#1]
The tiny turtle plan for ElephantSQL service [is no longer available](https://www.elephantsql.com/blog/turtle-discontinued.html). Can you recommend another free service ?

Thanks a lot !

**Comment by valentin-mille** [comment]
Maybe they were about to change it but it seems that's not the case right now. I am still able to use the tiny turtle plan. 

Just in case, Koyeb offers also a [database service](https://www.koyeb.com/docs/databases). You can use the latest `main` version and use `DATABASE_URL` env variable to use their own db easily.
